language: node_js
node_js:
  - 12

script:
  - npm install
  - npm run build
  - tar -zcvf release.tag.gz build/*
  - docker build -t admxj/real-subscribe .

deploy:
  provider: releases
  api_key: ${GITHUB_TOKEN}
  file:
    - release.tag.gz
  skip_cleanup: true
  on:
    tags: true