language: node_js
node_js:
  - 12
branches:
  only:
    - master
    - /^v.*$/
script:
  - yarn
  - yarn build
  - tar -zcvf release.tag.gz build/*
  - docker build -t admxj/real-subscribe .

before_deploy:
  - yarn
  - yarn build
  - tar -zcvf release.tag.gz build/*
deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file:
    - release.tag.gz
  skip_cleanup: true
  on:
    tags: true